<?php


namespace ProcessWire;


class ProcessSimpleAdminPage extends Process
{

    public static function getModuleInfo() {
        return array(
            'title' => 'Process Simple Admin Page',
            'summary' => 'Simple Process module that adds new admin page with',
            'version' => 001,
        );
    }
    public function execute() {
        return '
            <h2>Página creada al instalar el módulo</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam mattis eros vitae metus sodales eget suscipit purus rhoncus. Proin ultrices gravida dolor, non porttitor enim interdum vitae. Integer feugiat lacinia tincidunt. Nulla laoreet tristique tristique. Sed elementum justo a nisl elementum sit amet accumsan nisi tempor. Nulla quis eros et massa dignissim imperdiet a vitae purus.</p>
            ';
    }

    public function install(){
        // create new page to add to CMS
        $page = new Page();

        // add page attributes, I've called this page CMS FAQ'
        $page->template = "admin";
        $page->name = "cms-faq";
        $page->title = "CMS FAQ";
        $page->save();

        // set this module as the page process, this allows us to display the above
        $page->process = 'ProcessSimpleAdminPage';

        // get admin page and set as page parent
        $admin = $this->pages->get("id=2");
        $page->parent = $admin;

        // save page
        $page->save();
    }

    public function uninstall(){
        // delete created page
        $page = $this->pages->get("name=cms-faq");
        $this->pages->delete($page, true);

        //if(count($page)) $this->pages->delete($page, true);
    }
}